version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3010
    environment:
      - REACT_APP_REALT_PROPERTIES_BACKEND_URL=http://localhost:3000/
      - REACT_APP_REALT_THEGRAPH_URL=https://api.thegraph.com/subgraphs/name/realtoken-thegraph/
      - REACT_APP_REALT_THEGRAPH_GNOSIS=realtoken-xdai
      - REACT_APP_REALT_THEGRAPH_RMM=rmm-v3-wrapper-gnosis
    volumes:
      - ./frontend:/app
    command: [sh, -c, 'cd /app && npm start']

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - PORT=3000
      - CORS_ORIGIN=http://localhost
    volumes:
      - ./backend:/home/node/app
    command: [sh, -c, 'cd /home/node/app && npm run dev']