version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3010
    environment:
      - REACT_APP_REALT_PROPERTIES_BACKEND_URL=http://localhost:3000/
      - REACT_APP_REALT_COMMUNITY_URL=https://dashboard.realtoken.community/
      - REACT_APP_REALT_THEGRAPH_URL=https://gateway-arbitrum.network.thegraph.com/api/
      - REACT_APP_REALT_THEGRAPH_API_KEY=
      - REACT_APP_REALT_THEGRAPH_RMM=subgraphs/id/9Ut97U2oMKwRucppj7fdMeZ8oFCJrUYyr8wu4hFXBn7Y
      - REACT_APP_REALT_THEGRAPH_GNOSIS=subgraphs/id/FPPoFB7S2dcCNrRyjM5QbaMwKqRZPdbTg8ysBrwXd4SP
      - REACT_APP_REALT_THEGRAPH_ETH=subgraphs/id/EVjGN4mMd9h9JfGR7yLC6T2xrJf9syhjQNboFb7GzxVW
    volumes:
      - ./frontend:/app
    command: [sh, -c, 'cd /app && npm start']

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - PORT=3000
      - CORS_ORIGIN=http://localhost
      - REALT_COMMUNITY_URL=https://dashboard.realtoken.community/
    volumes:
      - ./backend:/home/node/app
    command: [sh, -c, 'cd /home/node/app && npm run dev']