name: Dev

on:
  pull_request:
    branches: [ main ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 23.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - name: Build
      run: npm run build
      working-directory: frontend

  # test_frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out code
  #     uses: actions/checkout@v3
  #   - name: Install dependencies
  #     run: npm ci
  #     working-directory: frontend
  #   - name: Test
  #     run: npm run test
  #     working-directory: frontend

  build_backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 23.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: backend
    - name: Build
      run: npm run build
      working-directory: backend
