name: Main Backend
on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  deploy-backend:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: backend
      context_path: backend
    secrets: inherit

  release-backend:
    concurrency: release
    uses: ./.github/workflows/reusable-release.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    with:
      working-directory: backend
      name: Backend
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}