name: Main Backend
on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  workflow_dispatch:

jobs:
    
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install jq
      run: sudo apt-get install jq
    - name: Read JSON file
      id: json
      run: |
        VALUE=$(jq -r '.version' ./backend/package.json)
        echo "::set-output name=value::$VALUE"
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:backend"
        tags: ${{ secrets.REPOSITORY }}:backend-latest,${{ secrets.REPOSITORY }}:backend-${{ steps.json.outputs.value }}
        labels: ${{ secrets.REPOSITORY }}:backend-latest,${{ secrets.REPOSITORY }}:backend-${{ steps.json.outputs.value }}

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
    - name: Execute commands over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.REPOSITORY }}:backend-latest

  restart-backend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
    - name: Execute commands over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker service update ${{ secrets.REPOSITORY }}_backend --force