name: Main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: frontend
      context_path: frontend
    secrets: inherit

  deploy-backend:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: backend
      context_path: backend
    secrets: inherit

  release:
    uses: ./.github/workflows/reusable-release.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    with:
      name: Monorepo
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}