name: Main Backend
on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**

jobs:
    
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:backend"
        tags: ${{ secrets.REPOSITORY }}:backend-latest
        labels: ${{ secrets.REPOSITORY }}:backend-latest
