name: Main Frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  deploy-frontend:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: frontend
      context_path: frontend
    secrets: inherit

  release-frontend:
    uses: ./.github/workflows/reusable-release.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    needs: deploy-frontend
    if: needs.deploy-frontend.result == 'success'
    with:
      working-directory: frontend
      name: Frontend
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}